ScheduleManager/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'top', to: 'homes#top'
  get 'about', to: 'homes#about'

  resources :users, only:[:edit,:update]
  get 'mypage', to: 'users#mypage'

  #イベント参加時

  #resources :event_join_statuses, only:[:create]

  resources :events, only:[:new,:create,:show,:update,:destroy,:edit,:index] do
    resources :comments, only:[:create,:destroy]
    resources :event_join_statuses, only:[:update,:destroy,:create]
  end
end

ScheduleManager/app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

ScheduleManager/app/views/layouts/_validation.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <div class="alert my-0 mr-0 ml-5 p-0"><%= message %></div>
  <% end %>
<% end %>

ScheduleManager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleManager</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- 画像スライドビュー用 -->

    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #65ace4;">
        <div class="container">
          <%= link_to "ScheduleManager", root_path, class: "navbar-brand" %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              <li class="nav-item">
                <%= link_to " イベントを開催する", new_event_path, class: "fas fa-calendar-plus nav-link text-dark" %>
              </li>

              <li class="nav-item">
                <%= link_to " 概要", about_path, class: "fas fa-question-circle nav-link text-dark" %>
              </li>
              <!-- ログイン済みの場合 -->
              <% if user_signed_in? %>

              <li class="nav-item">
                <%= link_to " マイページ", mypage_path, class: "fas fa-user nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to " ログアウトする", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-dark" %>
              </li>

              <!-- ログインしていない場合 -->
              <% elsif %>
              <li class="nav-item">
                <%= link_to " ログイン", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-dark" %>
              </li>
              <li class="nav-item">
                <%= link_to " ユーザー登録", new_user_registration_path, class: "fas fa-user-plus nav-link text-dark" %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= render 'layouts/notifications' %>
      <%= yield %>
    </main>

    <footer>
      <div class="container-fluid mt-3 bg-dark text-white">
        <div class="row">
          <div class="mx-auto my-5">
            <p class="text-center mb-0"></p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>