ScheduleManager/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'top', to: 'homes#top'
  get 'about', to: 'homes#about'

  resources :users, only:[:edit,:update]
  get 'mypage', to: 'users#mypage'

  #イベント参加時

  #resources :event_join_statuses, only:[:create]

  resources :events, only:[:new,:create,:show,:update,:destroy,:edit,:index] do
    resources :comments, only:[:create,:destroy]
    resources :event_join_statuses, only:[:update,:destroy,:create]
  end
end

ScheduleManager/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :event_images
  has_many :events
  has_many :comments, dependent: :destroy
  has_many :event_join_statuses, dependent: :destroy

  validates :name, presence: true
  validates :name, length: {maximum: 10}

  attachment :image
end

ScheduleManager/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

ScheduleManager/app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

ScheduleManager/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

ScheduleManager/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

ScheduleManager/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    mypage_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

ScheduleManager/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

ScheduleManager/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def mypage
    @user = User.find(current_user.id)
    if user_signed_in?
      @events = EventJoinStatus.where(user_id: current_user.id)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to mypage_path, notice: "編集が完了しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:image)
  end
end

ScheduleManager/app/helpers/users_helper.rb
module UsersHelper
end

ScheduleManager/app/views/users/edit.html.erb
<%= render partial: 'layouts/validation', locals: { model: @user }%>
<div class="container">
  <div class="row">
    <div class="col-md-5 my-5">
      <h1>ユーザー情報編集</h1>
    </div>
  </div>

  <%= form_with model: @user, local: true do |f| %>
  <div class="row form-group">
    <div class="col-md-3 offset-md-2">
      <p>アイコン</p>
    </div>
    <div class="col-md-4">
      <%= f.attachment_field :image, class: "form-control-file" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-3 offset-md-2">
      <p>ユーザー名</p>
    </div>
    <div class="col-md-4">
      <%= f.text_field :name, class: "form-control", value: @user.name, autofocus: true %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-3  offset-md-2">
      <p>メールアドレス</p>
    </div>
    <div class="col-md-4">
      <%= f.email_field :email, class: "form-control", value: @user.email %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-md-12 text-center">
      <%= f.submit '編集する', class: "btn btn-success mt-4" %>
    </div>
  </div>
  <% end %>
</div>

ScheduleManager/app/views/users/mypage.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 my-5">
      <h1>マイページ</h1>
    </div>
    <div class="col-md-6 d-flex flex-column justify-content-end align-items-end">
      <%= attachment_image_tag @user, :image, size:"100x100", fallback: "no_image.jpg", class: "rounded-circle mx-3 mt-4" %>

      <%= link_to "編集", edit_user_path(current_user.id), class: "btn btn-success col-md-3 m-2" %>
    </div>
  </div>


  <% if user_signed_in? %>
    <div class="row mt-3">
      <h3 class="col-md-12 ml-3">
        <%= @user.name %>さん の予定入力済みイベント
      </h3>
    </div>

    <div class="row mt-3">
      <table class="table table-hover table inverse col-md-12">
        <thead>
          <th class="table-active col-md-3" style="width:auto;">イベント名</th>
          <th class="table-active col-md-3" style="width:auto;">予定日時</th>
          <th class="table-active col-md-3" style="width:auto;">自分の参加予定</th>
        </thead>
        <tbody>
          <% @events.each do |f| %>
          <tr data-href="<%= event_path(f.event_id) %>", style="cursor: hand; cursor:pointer;">
            <td><%= f.event.event_name %></td>
            <td><%= l f.event.event_at, format: :schedule %></td>
            <td><%= f.status %></td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>


</div>