ScheduleManager/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'homes#top'
  get 'top', to: 'homes#top'
  get 'about', to: 'homes#about'

  resources :users, only:[:edit,:update]
  get 'mypage', to: 'users#mypage'

  #イベント参加時

  #resources :event_join_statuses, only:[:create]

  resources :events, only:[:new,:create,:show,:update,:destroy,:edit,:index] do
    resources :comments, only:[:create,:destroy]
    resources :event_join_statuses, only:[:update,:destroy,:create]
  end
end

ScheduleManager/app/models/event.rb
class Event < ApplicationRecord
  before_create :set_uuid

  has_many :users
  has_many :comments, dependent: :destroy
  has_many :event_join_statuses, dependent: :destroy

  validates :event_name,:event_at, presence: true
  validates :event_name, length: {maximum: 20}
  validates :user_name, presence: true
  validates :user_name, length: {maximum: 10}

  validate :event_at_cannot_be_in_the_past


  def event_at_cannot_be_in_the_past
    if event_at.present? && event_at.to_datetime < Date.today.to_time.to_datetime
      errors.add(:event_at, "は現在より過去の日時の指定はできません。")
    end
  end


  private
  def set_uuid
    while self.id.blank? || Event.find_by(id: self.id).present? do
      self.id = SecureRandom.uuid
    end
  end

end

ScheduleManager/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    #一度すべてを取得。オープンなイベントか否かを選択し、そのステータスカラムで条件を指定するように後程変更
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event_join_status = EventJoinStatus.create(
      status: 0,
      )

    if user_signed_in?
      #ユーザーがログインしていれば関連付けしたそのIDと名前をそのまま持ってくる
      @event.user_id = current_user.id
      @event.user_name = current_user.name

      @event_join_status.user_name = current_user.name
      @event_join_status.user_id = current_user.id
    else
      #ログインしていなければ入力されたuser_nameの情報を入れる、user_idは不要
      @event.user_name  = params[:event][:user_name]
      @event_join_status.user_name = @event.user_name
    end


    if @event.save
      if @event_join_status.update(event_id: @event.id)
        redirect_to event_path(@event.id), notice: "イベントを作成しました！URLを共有して予定を入力してもらいましょう！"
      else
        render :new
      end
    else
      render :new
    end
  end


  def show
    @event = Event.find(params[:id])
    @users = EventJoinStatus.where(event_id: @event.id)
    @comments = Comment.where(event_id: @event.id).reverse
    @comment = Comment.new
    @event_join_status = EventJoinStatus.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event.id), notice: '変更を保存しました。'
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    if event.destroy
      redirect_to mypage_path, notice: "イベントを削除しました。"
    else
      render root_path
    end
  end


  private
  def event_params
    params.require(:event).permit(:event_name,:event_at,:description,:user_name)
  end
end

ScheduleManager/app/helpers/events_helper.rb
module EventsHelper
end

ScheduleManager/app/views/events/edit.html.erb
<%= render partial: 'layouts/validation', locals: { model: @event }%>
<div class="container">
  <div class="row">
    <div class="col-md-5 my-5">
      <h1>イベントを編集する</h1>
    </div>
  </div>

  <%= form_with model: @event, url: event_path, local: true do |f| %>
    <div class="form-group row">
      <%= f.label "イベント名", class: "col-md-3 offset-md-2" %>
      <%= f.text_field :event_name, class: "form-control col-md-5" %>
    </div>

    <div class="form-group row">
      <%= f.label "日付", class: "col-md-3 offset-md-2" %>
      <%= f.datetime_field :event_at, class: "form-control col-md-5" %>
    </div>

    <div class="form-group row">
      <%= f.label "イベントの説明", class: "col-md-3 offset-md-2" %>
      <%= f.text_area :description, class: "form-control col-md-5" %>
    </div>


    <% unless user_signed_in? %>
    <!-- ログインしてるかつ、ログインしてるユーザーが作成ユーザーと同じ時のみ表示に変更すること -->
      <div class="form-group row">
        <%= f.label "イベント主催者", class: "col-md-3 offset-md-2" %>
        <%= f.text_field :user_name, class: "form-control col-md-5", placeholder: "名無し" %>
      </div>
    <% end %>

    <div class="form-group text-center btn-lg">
      <%= f.submit "更新する", class: "btn btn-primary mx-3 my-2", style: "width: 240px; height: 50px" %>
    </div>

  <% end %>

ScheduleManager/app/views/events/index.html.erb
<% @events.each do |f| %>
  <%= f.event_name %>
  <%= f.event_at %>
<% end %>

ScheduleManager/app/views/events/new.html.erb
<%= render partial: 'layouts/validation', locals: { model: @event }%>
<div class="container">
  <div class="row">
    <div class="col-md-5 my-5">
      <h1>イベントを作成する</h1>
    </div>
  </div>

  <%= form_with model: @event, url: events_path, local: true do |f| %>
    <div class="form-group row">
      <%= f.label "イベント名", class: "col-md-3 offset-md-2" %>
      <%= f.text_field :event_name, class: "form-control col-md-5", placeholder: "Zoom飲み会、4/1に見に行く映画" %>
    </div>

    <div class="form-group row">
      <%= f.label "日付", class: "col-md-3 offset-md-2" %>
      <%= f.datetime_field :event_at, class: "form-control col-md-5" %>
    </div>

    <div class="form-group row">
      <%= f.label "イベントの説明", class: "col-md-3 offset-md-2" %>
      <%= f.text_area :description, class: "form-control col-md-5", placeholder: "チームの打ち上げでZoom飲み会をしましょう！経費で飲めます！" %>
    </div>


    <% unless user_signed_in? %>
      <div class="form-group row">
        <%= f.label "イベント主催者", class: "col-md-3 offset-md-2" %>
        <%= f.text_field :user_name, class: "form-control col-md-5", placeholder: "名無し" %>
      </div>
    <% end %>

    <div class="form-group text-center btn-lg">
      <%= f.submit "イベントを作成する", class: "btn btn-success mx-3 my-2", style: "width: 240px; height: 50px" %>
    </div>

  <% end %>
</div>

ScheduleManager/app/views/events/show.html.erb
<%= render partial: 'layouts/validation', locals: { model: @event_join_status } %>
<%= render partial: 'layouts/validation', locals: { model: @comment } %>
<div class="container">
  <div class="row">
    <div class="col-lg-5 my-5">
      <h1><%= @event.event_name %></h1>
    </div>
    <div class="col-lg-7 d-flex flex-column justify-content-end align-items-end">
      <div class="d-flex-inline">
        <!-- @eventモデルのuser_idが空（非ログインユーザーで作成されたもの）だったら誰でも編集可能
         また、user_idが入っている場合ログインしてるユーザーと一致すれば、その人のみが編集可能 -->
        <% if @event.user_id != nil %>
          <% if user_signed_in? %>
            <% if @event.user_id == current_user.id %>
              <%= link_to "イベントを編集する", edit_event_path(@event.id), class: "btn btn-success m-2" %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to "イベントを編集する", edit_event_path(@event.id), class: "btn btn-success m-2" %>
        <% end %>

        <!-- ログインしているかつ、ログインしているユーザーとイベント作成者のURLが同じ場合のみ表示 -->
        <% if user_signed_in? %>
          <% if @event.user_id == current_user.id %>
            <%= link_to "イベントを削除する", event_path(@event.id), method: :delete, class:"btn btn-danger my-2 ml-2",
            data: {confirm: "このイベント【" + @event.event_name + "】を削除しますか？"} %>
          <% end %>
        <% end %>
      </div>
      <div class="bd-highlight">予定日時：<%= l @event.event_at, format: :schedule %></div>
      <div class="bd-highlight">オーナー：<%= @event.user_name %></div>
      <div class="bd-highlight">簡単な説明：<%= @event.description %></div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <b><p>参加する：<%= @users.where(status: 0).count %>人　　保留：<%= @users.where(status: 1).count %>人　　参加しない：<%= @users.where(status: 2).count %>人</p></b>
    </div>
  </div>


  <div class="row m-3">
    <%= form_with model: [@event,@event_join_status], url: event_event_join_statuses_path(@event.id), local: true do |f| %>
      <%= f.label "名前を入れて予定を入力する" %>
      <div class="d-flex">
        <%= f.hidden_field :user_id, value: nil %>
        <%= f.hidden_field :status, value: "参加する" %>
        <%= f.text_field :user_name, placeholder: "名前", class: "form-control ml-2" %>
        <%= f.submit "予定を入力する", class: "btn btn-success ml-3" %>
      </div>
    <% end %>
  </div>

  <!-- 既に参加しているユーザーIDは省く -->
  <% if user_signed_in? && @event.event_join_statuses.where(user_id: current_user.id).blank? %>
    <div class="row m-3">
      <%= form_with model: [@event,@event_join_status], url: event_event_join_statuses_path(@event.id), local: true do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :status, value: "参加する" %>
        <%= f.hidden_field :user_name, value: current_user.name %>
        <%= f.submit "ログインしているユーザー名で予定を入力する", class: "btn btn-primary ml-2" %>
      <% end %>
    </div>
  <% end %>

  <div class="text-right mb-3">
    <button class="slideBoxOnOff btn btn-outline-info align-items-right">投稿された画像を表示/非表示させる</button>
  </div>
  <ul class="slideBox">
    <% @comments.each do |f| %>
      <% if f.image_id.present? %>
        <li class="imgOnOff">
          <%= attachment_image_tag f, :image, size:"100%x100%", class: "slideImg" %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <div class="row mt-3">
    <table class="table col-lg-6" style="table-layout:fixed; height:170px;">
      <thead class="thead-light">
        <th style="width:65px;"></th>
        <th style="width:100px;">
          名前
        </th>
        <th style="width:auto;">
          予定状況
        <th style="width:100px;"></th>
      </thead>

      <tbody>
        <% @users.each do |f| %>
        <tr>
          <td class="align-middle">
            <% unless f.user_id.blank? %>
              <%= attachment_image_tag f.user, :image, size:"50x50", fallback: "no_image.jpg", class: "rounded-circle" %>
            <% end %>
          </td>
          <td class="align-middle" style="word-wrap:break-word; width:200px;">
            <!-- 非登録ユーザー（idが格納されていない）人のみ名前表示（DBの設計ミス） -->
            <% if f.user_id.blank? %>
              <%= f.user_name %>
            <% else %>
              <%= f.user.name %>
            <% end %>
          </td>
          <td class="form-inline">
            <div class="d-flex align-items-center">
            <%= form_with model: [@event,f], url: event_event_join_status_path(@event.id,f.id), method: :patch, local: true do |f| %>
              <%= f.select :status, EventJoinStatus.statuses.keys.to_a, {}, class: "form-control" %>
              <%= f.submit "更新", class: "btn btn-success btn-sm ml-3" %>
            <% end %>
            </div>
          </td>
          <td class="align-middle">
             <%= link_to "削除", event_event_join_status_path(@event, f.id), method: :delete, data: {confirm: "この予定を削除しますか？"}, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="col-lg-6">
      <div>
        <%= form_with model: [@event,@comment], local: true do |f| %>
          <% unless user_signed_in? %>
            <%= f.label "名前" %>
            <%= f.text_field :user_name, placeholder: "名前", class: "form-control" %>
          <% else %>
            <%= attachment_image_tag current_user, :image, size:"75x75", fallback: "no_image.jpg", class: "rounded-circle" %>
            <%= current_user.name %>
          <% end %>

          <div class="form-group mt-2">
            <%= f.label "コメントする" %>
            <%= f.text_area :comment, placeholder: "コメントを入力", class: "form-control" %>
          </div>


          <div class="text-right m-3 mb-4 form-group">
            <%= f.attachment_field :image, class: "form-control-file" %>
            <%= f.submit "投稿する", class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
      </div>

      <div>

      <% @comments.each do |f| %>
        <div class="row mt-3 justify-content-between d-flex p-1 rounded border">
          <div class="col-lg-2 mt-3">
            <%= attachment_image_tag f.user, :image, size:"75x75", fallback: "no_image.jpg", class: "rounded-circle" %>
          </div>


          <div class="col-lg-10">
            <div class="justify-content-between d-flex">
              <p class="ml-4 mt-2">
                <% if f.user_id.blank? %>
                  <%= f.user_name %>
                <% else %>
                  <%= f.user.name %>
                <% end %>
              </p>
              <p class="text-right mr-4"><%= l f.created_at, format: :comment %></p>
            </div>

            <div class="row d-flex align-items-center">
              <div class="ml-4 p-1 says">
                <p class="m-2"><%= f.comment %></p>
              </div>

              <% if user_signed_in? %>
                <div class="col-lg-2">
                  <% if f.user_id == current_user.id %>
                    <div class="text-right">
                      <%= link_to "削除", event_comment_path(f.event_id,f.id), method: :delete,
                        data: {confirm: "このコメントを削除しますか？"}, class: "btn btn-danger btn-sm my-2" %>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      </div>

    </div>
  </div>
</div>